# Catppuccin Macchiato tmux theme

set -g status-style "bg=#24273a,fg=#cad3f5"
set -g status-left-style "bg=#363a4f,fg=#f5bde6,bold"
set -g status-right-style "bg=#363a4f,fg=#a6da95"
set -g window-status-current-style "bg=#494d64,fg=#f5bde6,bold"
set -g window-status-style "bg=#24273a,fg=#8aadf4"
set -g pane-border-style "fg=#5b6078"
set -g pane-active-border-style "fg=#f5bde6"
set -g message-style "bg=#363a4f,fg=#cad3f5"
set -g mode-style "bg=#494d64,fg=#eed49f"
