# Kanagawa tmux theme

set -g status-style "bg=#1f1f28,fg=#dcd7ba"
set -g status-left-style "bg=#2d4f67,fg=#7e9cd8,bold"
set -g status-right-style "bg=#2d4f67,fg=#76946a"
set -g window-status-current-style "bg=#363646,fg=#e6c384,bold"
set -g window-status-style "bg=#1f1f28,fg=#727169"
set -g pane-border-style "fg=#54546d"
set -g pane-active-border-style "fg=#7e9cd8"
set -g message-style "bg=#2d4f67,fg=#dcd7ba"
set -g mode-style "bg=#363646,fg=#e6c384"
