# Nord tmux theme

set -g status-style "bg=#2e3440,fg=#d8dee9"
set -g status-left-style "bg=#3b4252,fg=#88c0d0,bold"
set -g status-right-style "bg=#3b4252,fg=#a3be8c"
set -g window-status-current-style "bg=#434c5e,fg=#88c0d0,bold"
set -g window-status-style "bg=#2e3440,fg=#81a1c1"
set -g pane-border-style "fg=#4c566a"
set -g pane-active-border-style "fg=#88c0d0"
set -g message-style "bg=#3b4252,fg=#e5e9f0"
set -g mode-style "bg=#434c5e,fg=#ebcb8b"
